actions_terms = {"out":"SUB",
                "in":"FOR",
                "2m":"MADE 2PT", 
                "3m":"MADE 3PT", 
                "1m":"MADE FT", 
                "f0":"FOUL", 
                "f1":"FOUL", 
                "f2":"FOUL", 
                "f3":"FOUL", 
                "ft":"TECHNICAL FOUL",
                "fu":"UNSPORTSMANLIKE FOUL",
                "fd":"DISQUALIFIED",
                "r":"REBOUND", 
                "a":"AST", 
                "s":"STEAL", 
                "b":"BLOCK", 
                "2":"MISS 2PT", 
                "3":"MISS 3PT", 
                "1":"MISS FT", 
                "t":"TURNOVER",
                "j":"POSSESSION AFTER JUMP BALL",
                "to":"TIMEOUT"}

team_terms =    {"H":"HOME",
                "A":"AWAY"}

quarter_terms = {"1":"1st QUARTER",
                "2":"2nd QUARTER",
                "3":"3rd QUARTER",
                "4":"4th QUARTER",
                "5":"1st OVERTIME",
                "6":"2nd OVERTIME",
                "7":"3rd OVERTIME",
                "8":"4th OVERTIME"}

actions_terms_lower = {"out":"sub",
                       "in":"for",
                       "2m":"made 2pt",
                       "3m":"made 3pt", 
                       "1m":"made ft", 
                       "f0":"foul", 
                       "f1":"foul", 
                       "f2":"foul", 
                       "f3":"foul", 
                       "ft":"technical foul",
                       "fu":"unsportsmanlike foul",
                       "fd":"disqualified",
                       "r":"rebound",
                       "a":"assist", 
                       "s":"steal", 
                       "b":"block", 
                       "2":"miss 2pt",
                       "3":"miss 3pt", 
                       "1":"miss ft", 
                       "t":"turnover",
                       "j":"possession (after jump ball)",
                       "to":"timeout"}

team_terms_lower = {"H":"home",
                    "A":"away"}

quarter_terms_lower = {"1":"1st quarter",
                       "2":"2nd quarter",
                       "3":"3rd quarter",
                       "4":"4th quarter",
                       "5":"1st overtime",
                       "6":"2nd overtime",
                       "7":"3rd overtime",
                       "8":"4th overtime"}

actions_code = {"out":"Substitution",
                "2m":"FieldGoalMade", 
                "3m":"FieldGoalMade", 
                "1m":"FreeThrowMade", 
                "f0":"PersonalFoul", 
                "f1":"ShootingFoul", 
                "f2":"ShootingFoul", 
                "f3":"ShootingFoul", 
                "ft":"TechnicalFoul",
                "fu":"UnsportsmanlikeFoul",
                "fd":"Disqualification",
                "r":"Rebound", 
                "s":"Steal", 
                "b":"Block", 
                "2":"FieldGoalMissed", 
                "3":"FieldGoalMissed", 
                "1":"FreeThrowMissed", 
                "t":"Turnover",
                "j":"JumpBall",
                "to":"Timeout"}

quarter_code = {"1":"1st Quarter",
                "2":"2nd Quarter",
                "3":"3rd Quarter",
                "4":"4th Quarter",
                "5":"1st Overtime",
                "6":"2nd Overtime",
                "7":"3rd Overtime",
                "8":"4th Overtime"}